<?php
/** op-asset-bootstrap:/template/php/module.phtml
 *
 * @created   2016-11-16
 * @moved     2025-04-12
 * @version   1.0
 * @package   op-asset-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<?php require(__DIR__.'/../html_head.phtml') ?>
		<section>
			<h1>Does not install php-<?= _OP_APP_BOOTSTRAP_ ?> module.</h1>
			<p>Please install php-<?= _OP_APP_BOOTSTRAP_ ?> module.</p>
			<?php
			switch( PHP_OS ){ // PHP 7.2.0 --> PHP_OS_FAMILY
				case 'MacOS':
				case 'Darwin':
					include('module-osx.phtml');
					break;

				case 'WIN32':
				case 'WINNT':
					include('module-win.phtm.phtml');
					break;

				case 'AIX':
				case 'Linux':
				case 'SunOS':
					include('module-unix.phtml');
					break;

				default:
					echo PHP_OS . PHP_EOL;
					break;
			}
			?>
		</section>
<?php require(__DIR__.'/../html_foot.phtml') ?>
