<?php
/** op-asset-bootstrap:/template/php/module-osx.phtml
 *
 * @created   2018-11-13
 * @version   1.0
 * @package   op-asset-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	...
$v = PHP_MAJOR_VERSION . PHP_MINOR_VERSION;

//	...
if( preg_match('/apache/', PHP_SAPI) ){
	$target = 'apache2';
}else if( preg_match('/cgi/', PHP_SAPI) ){
	$target = "php{$v}-fpm";
}else{
	$target = null;
}
?>
	<section>
		<h2>MacPorts</h2>
		<pre><code><?= null /* PHP Zend Engine will remove EOL. */ ?>
sudo port install php<?= $v ?>-<?= _OP_APP_BOOTSTRAP_ . PHP_EOL ?>
sudo port unload <?= $target.PHP_EOL ?>
sudo port load <?= $target ?>
		</code></pre>
	</section>
