<?php
/**	op-module-bootstrap:/op/rewrite-litespeed.phtml
 *
 * @created    2024-11-19
 * @version    1.0
 * @package    op-module-bootstrap
 * @author     Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	Declare strict
 *
 */
declare(strict_types=1);

/**	namespace
 *
 */
namespace OP;

/*
//	Generate app root.
$doc = realpath($_SERVER['DOCUMENT_ROOT']);
$dir = realpath(__DIR__); // git:/asset/bootstrap/op/
$pos = strpos($dir, $doc);
if( $pos === false ){
	//	asset dir is not under doc root.
	$app_root = '/';
}else if( $pos === 0 ){
	$dir = dirname($dir); // git:/asset/bootstrap/
	$dir = dirname($dir); // git:/asset/
	$dir = dirname($dir); // git:/
	$app_root = rtrim($dir, '/') . '/';
}else{
	echo "<p>app root is not found.</p>";
	return;
}
*/

?>
<div data-translate="popup">
<h1>How to boot the onepiece-framework at the LiteSpeed Web Server.</h1>
<ol>
	<li>Click `Virtual Hosts` from Left menu</li>
	<li>Click target virtual host name</li>
	<li>Click `Rewrite` tab</li>
	<li>Change the values ​​as follows:
		<ol>
			<li>Enable Rewrite : `Yes`</li>
			<li>Rewrite Rules:
<pre><code>
# Enable rewrite engine.
RewriteEngine On

# If file does not exists, Dispatched to app.php.
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . <?= rtrim($_SERVER['REQUEST_URI'],'/') ?>/app.php [END]

# If the file exists, Dispatch only this extension.
RewriteCond %{REQUEST_FILENAME} -f
RewriteCond %{REQUEST_URI} \.(php|html|js|css|txt)$
RewriteRule . <?= rtrim($_SERVER['REQUEST_URI'],'/') ?>/app.php [END]
</code></pre>
				<hr/>
				<img src="//onepiece-framework.com/img/rewrite-litespeed.png"
					 alt="rewrite-litespeed"
					 style="max-width:80%;" />
			</li>
		</ol>
	</li>
</ol>
</div>
