<?php
/** op-asset-bootstrap:/template/op/failed.phtml
 *
 * @created   2016-11-25
 * @version   1.0
 * @package   op-asset-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-20
 */
namespace OP;

?>
<!doctype html>
<html>
	<head>
		<title>The onepiece-framework bootstrap was failed.</title>
	</head>
	<body>
		<header>
			onepiece-framework
		</header>
		<hr/>
		<h1>The onepiece-framework bootstrap was failed.</h1>
			<?php
				//	...
				/* @var $e \Exception */
				echo '<h2>'.$e->getMessage().'</h2>'.PHP_EOL;

				//	...
				echo '<ol>'.PHP_EOL;
				foreach( $e->getTrace() as $backtrace ){
					$file = $backtrace['file']     ?? null;
					$line = $backtrace['line']     ?? null;
					$func = $backtrace['function'] ?? null;
					$clss = $backtrace['class']    ?? null;
					$type = $backtrace['type']     ?? null;
					$args = $backtrace['args']     ?? null;
					$join = [];
					$argument = null;

					//	...
					switch( $type ){
						case '::':
						case '->':
							$order = $clss.$type.$func;
							break;
						default:
							$order = $func;
					}

					//	...
					if( $args === null ){
						$argument = 'null';
					}else{
						foreach( $args as $arg ){
							switch( $type = gettype($arg) ){
								case 'string':
									$join[] = "\"$arg\"";
									break;

								case 'array':
									$count  = count($arg);
									$join[] = "array($count)";
									break;

								default:
									$join[] = $type;
							}
						}
						$argument = join(', ', $join);
					}

					//	...
					echo "<li>{$file} #{$line} {$order}($argument)</li>".PHP_EOL;
				}
				echo '</ol>'.PHP_EOL;
			?>
		<hr/>
		<footer>
			Copyright 2009 onepiece-framework all right reserved
		</footer>
	</body>
</html>
